## Numpy

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# creating arrays

In [4]:
sample_array = np.array([1,2,3,4])

In [5]:
sample_array

array([1, 2, 3, 4])

In [8]:
#2D Array
# 2 rows and 2 col

In [10]:
sample_array2 = np.array([[1,2],[3,4]])

In [11]:
sample_array2

array([[1, 2],
       [3, 4]])

In [12]:
#3D Tensor (2 matrices ,Each with 2 rows and 2 cols)

In [13]:
sm_3 = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])

In [14]:
sm_3

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [ ]:
sm_4 = 

In [15]:
# Dimension 

In [17]:
# 0-D Array (=>scaler) 5
# 1-D Array (Vector) [1,2,3,4]
# 2-D Array (Matrix) {rows,cols}
# 3-D Array (Tensor) {page,row,column}

In [18]:
#array properties

In [19]:
sample_array3 = np.array([[10,20,30],[50,60,70]])

In [20]:
sample_array3

array([[10, 20, 30],
       [50, 60, 70]])

In [21]:
sample_array3.shape

(2, 3)

In [22]:
#dimensions

In [23]:
sample_array3.ndim

2

In [24]:
# total elements

In [25]:
sample_array3.size

6

In [26]:
sample_array3.dtype

dtype('int64')

In [27]:
# speacial Arrays

In [32]:
np.zeros((20,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [36]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [39]:
sample_array = np.array([10,20,30,40])

In [40]:
sample_array

array([10, 20, 30, 40])

In [41]:
sample_array[0]

np.int64(10)

In [42]:
sample_array[3]

np.int64(40)

In [43]:
sample_array[-1]

np.int64(40)

In [44]:
# Slicing

In [45]:
sample_array[1:3]

array([20, 30])

In [46]:
a = np.array([20,40,60])

In [47]:
b = np.array([10,30,50])

In [48]:
a

array([20, 40, 60])

In [49]:
b

array([10, 30, 50])

In [50]:
a + b

array([ 30,  70, 110])

In [51]:
a - b

array([10, 10, 10])

In [52]:
b - a

array([-10, -10, -10])

In [53]:
a * b

array([ 200, 1200, 3000])

In [54]:
a / b

array([2.        , 1.33333333, 1.2       ])

In [55]:
b / a


array([0.5       , 0.75      , 0.83333333])

In [56]:
# Mathematical Functions

In [59]:
sample_array = np.array([1,4,9])
sample_array

array([1, 4, 9])

In [60]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [61]:
sm_4 = np.array([100,200,32984300])
sm_4

array([     100,      200, 32984300])

In [62]:
np.sqrt(sm_4)

array([  10.        ,   14.14213562, 5743.19597437])

In [64]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [65]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [66]:
#statistical functions

In [67]:
sample_array2 = np.array([1,2,3,4,5])
sample_array2

array([1, 2, 3, 4, 5])

In [68]:
np.mean(sample_array2)

np.float64(3.0)

In [69]:
np.median(sample_array2)

np.float64(3.0)

In [74]:
np.std(sample_array)




np.float64(3.2998316455372216)

In [73]:
np.std(sample_array2)

np.float64(1.4142135623730951)

In [72]:
np.std(sm_3)

np.float64(2.7386127875258306)

In [71]:
np.std(sm_4)

np.float64(15548877.424503103)

In [76]:
sample_array2 = np.arange(6)
sample_array2

array([0, 1, 2, 3, 4, 5])

In [77]:
reshaped = sample_array2.reshape(2,3)
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
# flatenning


In [79]:
sample_arrayx = np.array([[10,20],[30,40]])
sample_arrayx.flatten()

array([10, 20, 30, 40])

In [81]:
sample_arrayx = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
sample_arrayx.flatten()

array([1, 2, 3, 4, 6, 7, 8, 9])

In [82]:
# Joining Array

In [83]:
a = np.array([1,2])

In [ ]:
b = np.array([3,4])

In [91]:
np.concat((a,b))

array([1, 2, 3, 4])

In [92]:
#spliting arrays

In [98]:
ar = np.array([1,2,3,4,5,6,7,78,100])

In [99]:
ar

array([  1,   2,   3,   4,   5,   6,   7,  78, 100])

In [103]:
np.array_split(ar,8)

[array([1, 2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([78]),
 array([100])]

In [106]:
np.random

<module 'numpy.random' from 'd:\\Datasci\\Software\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [107]:
# Axis Concept

In [108]:
sm = np.array([[1,2],[3,4]])

In [109]:
sm 


array([[1, 2],
       [3, 4]])

In [110]:
np.sum(sm,axis=0)

array([4, 6])

In [111]:
np.sum(sm,axis=1)

array([3, 7])

In [112]:
# create two numpy arrays and perform element vise addition, subtraction, multiplication , division and modulus 

In [113]:
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([3,  4,  5,  6,  7])
addition = np.add(array1, array2)
print("np.add():       ", addition)
subtraction = np.subtract(array1, array2)
print("np.subtract():  ", subtraction)
multiplication = np.multiply(array1, array2)
print("np.multiply():  ", multiplication)
division = np.divide(array1, array2)
print("np.divide():    ", division)
#
modulus = np.mod(array1, array2)
print("np.mod():       ", modulus)

np.add():        [13 24 35 46 57]
np.subtract():   [ 7 16 25 34 43]
np.multiply():   [ 30  80 150 240 350]
np.divide():     [3.33333333 5.         6.         6.66666667 7.14285714]
np.mod():        [1 0 0 4 1]
